[2022-01-14 00:05:21,954] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: my_dag_anp.rfn_sales_diesel scheduled__2022-01-13T00:00:00+00:00 [queued]>
[2022-01-14 00:05:21,973] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: my_dag_anp.rfn_sales_diesel scheduled__2022-01-13T00:00:00+00:00 [queued]>
[2022-01-14 00:05:21,974] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-14 00:05:21,975] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-14 00:05:21,975] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-14 00:05:22,011] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): rfn_sales_diesel> on 2022-01-13 00:00:00+00:00
[2022-01-14 00:05:22,018] {standard_task_runner.py:52} INFO - Started process 2229 to run task
[2022-01-14 00:05:22,024] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag_anp', 'rfn_sales_diesel', 'scheduled__2022-01-13T00:00:00+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/my_dag_anp.py', '--cfg-path', '/tmp/tmp309qp4uy', '--error-file', '/tmp/tmp8tujn5ik']
[2022-01-14 00:05:22,026] {standard_task_runner.py:77} INFO - Job 60: Subtask rfn_sales_diesel
[2022-01-14 00:05:22,116] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag_anp.rfn_sales_diesel scheduled__2022-01-13T00:00:00+00:00 [running]> on host 9ef8a6cbe880
[2022-01-14 00:05:22,177] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag_anp
AIRFLOW_CTX_TASK_ID=rfn_sales_diesel
AIRFLOW_CTX_EXECUTION_DATE=2022-01-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-13T00:00:00+00:00
[2022-01-14 00:05:22,353] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/utils.py", line 313, in run_rfn_sales_diesel
    os.remove(sink)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/sink/rfn/rfn_sales_diesel.parquet'
[2022-01-14 00:05:22,374] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=my_dag_anp, task_id=rfn_sales_diesel, execution_date=20220113T000000, start_date=20220114T000521, end_date=20220114T000522
[2022-01-14 00:05:22,395] {standard_task_runner.py:92} ERROR - Failed to execute job 60 for task rfn_sales_diesel
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/utils.py", line 313, in run_rfn_sales_diesel
    os.remove(sink)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/sink/rfn/rfn_sales_diesel.parquet'
[2022-01-14 00:05:22,445] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-01-14 00:05:22,516] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
