[2022-01-12 22:59:06,101] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate manual__2022-01-12T22:59:01.118387+00:00 [queued]>
[2022-01-12 22:59:06,113] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate manual__2022-01-12T22:59:01.118387+00:00 [queued]>
[2022-01-12 22:59:06,113] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-12 22:59:06,113] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-01-12 22:59:06,113] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-12 22:59:06,128] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): inaccurate> on 2022-01-12 22:59:01.118387+00:00
[2022-01-12 22:59:06,132] {standard_task_runner.py:52} INFO - Started process 2627 to run task
[2022-01-12 22:59:06,135] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'manual__2022-01-12T22:59:01.118387+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpvkae0vg5', '--error-file', '/tmp/tmps3li5nhp']
[2022-01-12 22:59:06,135] {standard_task_runner.py:77} INFO - Job 13: Subtask inaccurate
[2022-01-12 22:59:06,182] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.inaccurate manual__2022-01-12T22:59:01.118387+00:00 [running]> on host 5ffba7c75690
[2022-01-12 22:59:06,231] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-01-12T22:59:01.118387+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-12T22:59:01.118387+00:00
[2022-01-12 22:59:06,233] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-01-12 22:59:06,233] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'inaccurate'"]
[2022-01-12 22:59:06,242] {subprocess.py:85} INFO - Output:
[2022-01-12 22:59:06,243] {subprocess.py:89} INFO - inaccurate
[2022-01-12 22:59:06,244] {subprocess.py:93} INFO - Command exited with return code 0
[2022-01-12 22:59:06,268] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20220112T225901, start_date=20220112T225906, end_date=20220112T225906
[2022-01-12 22:59:06,307] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-12 22:59:06,356] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
